services:
  - type: web
    name: compilers1
    env: node
    buildCommand: "npm install && sudo apt-get update && sudo apt-get install -y openjdk-11-jdk"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
